### ISSUE TITLE
get_header() doesn't behave well

### ISSUE THREAD

**Issue by tycho** [dw/csvmonkey#4] opened 2019-05-19 12:47 UTC
I was going to try this out in my project but ran into a problem.

I'm doing `csvmonkey.from_file(fd, header=True)` (where `fd` is an open handle from `zipfile.ZipFile.open(filename)`). If I do `.get_header()` immediately after attaching csvmonkey to the handle, it returns the header strangely concatenated with the first line after it. `repr(header)` looks like:

> ['network', 'autonomous_system_number,autonomous_system_organization\n2001:200::/37', '2500', 'WIDE Project']

The datasource is the [GeoLite2 ASN CSV](https://dev.maxmind.com/geoip/geoip2/geolite2-asn-csv-database/).

`head` of the extracted input CSV looks like this:
```
==> GeoLite2-ASN-Blocks-IPv6.csv <==
network,autonomous_system_number,autonomous_system_organization
2001:200::/37,2500,"WIDE Project"
2001:200:800::/40,2500,"WIDE Project"
2001:200:900::/40,7660,"Asia Pacific Advanced Network - Japan"
2001:200:a00::/39,2500,"WIDE Project"
2001:200:c00::/38,2500,"WIDE Project"
2001:200:1000::/36,2500,"WIDE Project"
```

**Comment by dw** [comment] 2019-05-19 13:18
It may be a line endings problem, I'll take a look. This is why the readme still mentions 'toy code' :)  I'm really only testing it with one type of input fie just now

**Comment by dw** [comment] 2019-05-19 13:24
Reproduction script:

````python
[14:23:18 eldil!49 csvm] cat a.py 

import zipfile

zf = zipfile.ZipFile('GeoLite2-ASN-CSV.zip')

fd = zf.open('GeoLite2-ASN-CSV_20190514/GeoLite2-ASN-Blocks-IPv6.csv')
print(fd)


import csvmonkey

reader = csvmonkey.from_file(fd, header=True)
print(reader)

````

Steps:

````
[14:23:47 eldil!54 csvm] wget http://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN-CSV.zip
--2019-05-19 14:23:49--  http://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN-CSV.zip
Resolving geolite.maxmind.com (geolite.maxmind.com)... 104.17.200.89, 104.17.201.89, 2606:4700::6811:c959, ...
Connecting to geolite.maxmind.com (geolite.maxmind.com)|104.17.200.89|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4671569 (4.5M) [application/zip]
Saving to: ‘GeoLite2-ASN-CSV.zip’

GeoLite2-ASN-CSV.zip                        100%[=========================================================================================>]   4.46M  1.46MB/s    in 3.1s    

2019-05-19 14:23:52 (1.46 MB/s) - ‘GeoLite2-ASN-CSV.zip’ saved [4671569/4671569]

[14:23:52 eldil!55 csvm] PYTHONINSPECT=1 python a.py 
<zipfile.ZipExtFile name='GeoLite2-ASN-CSV_20190514/GeoLite2-ASN-Blocks-IPv6.csv' mode='r' compress_type=deflate>
<csvmonkey._Reader positioned at record 0>
>>> reader.get_header()
['network', 'autonomous_system_number,autonomous_system_organization\n2001:200::/37', '2500', 'WIDE Project']
>>> 

````

**Comment by dw** [comment] 2019-05-19 13:26
Whoa, that's really broken. It's somehow dropping a whole column too ('autonomous_us_system_number')

It's unrelated to from_file() vs. from_path(), i.e. not a `StreamCursor` implementation bug, it's a parsing bug.

**Comment by dw** [comment] 2019-05-19 13:30
The problem was due to cutpasting some code from the quoted cell case -- and using the wrong spanner instance (which was searching for a quote mark, not command/newline). It's fixed in master

**Comment by dw** [comment] 2019-05-19 13:33
The real bug here is that I hate setting up cmake projects :)  And until that's done, there is no automated testing :)

**Comment by tycho** [comment] 2019-05-19 13:41
Awesome, thanks for fixing it so quickly! It now works for my use case.

Also CMake isn't *that* horrible. It's probably the second or third least painful of the build system options out there.

**Comment by dw** [comment] 2019-05-19 13:54
It sounds like we have a cmake volunteer! 😁

I've never done a header-only library in cmake before, and I know things have progressed in cmake land to make projects more packageable. I wanted to figure out how all that works, that's why it's been delayed so far

**Comment by dw** [comment] 2020-02-25 09:34
I'm not working on this right now. Closing the ticket and making the repo PR only. Apologies for the inconvenience -- feel free to send patches. :)  Thanks

**Closed by dw** 2020-02-25 09:34 UTC
